import './globals.css';
import type { Metadata } from 'next';
import SessionProvider from './components/SessionProvider';
import { getServerSession } from 'next-auth';
import { Montserrat } from 'next/font/google';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const montserrat = Montserrat({ subsets: ['latin'] });

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();
  return (
    <html lang='en'>
      <body className={montserrat.className}>
        <SessionProvider session={session}>{children}</SessionProvider>
      </body>
    </html>
  );
}
